// Generated by https://quicktype.io

import { IProducto } from "./IProductos";

export interface ICategoria{
    catid:  string;
    nombre: string;
    desc:   string;
    producto?: IProducto[];
}
